### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ylvakiller** [4o66/KSP-Mod-Admin#2]
Hi there,
I was wondering if it would be possible to add sites to the recognized site lists (where you might have to select the download link manually),Sites that are often used like:
curse.com (to allow for example mods to be downloaded and managed via a following link:http://www.curse.com/ksp-mods/kerbal/223932-b9-aerospace-5-2-8)
https://kerbalstuff.com/ (has tons of mods, and often links from forums let you download their mod via kerbalstuff)
Maybe it would be best to not check for a specific url, but instead just look for a download link (maybe add this as option, where you only enter a download link?)

**Comment by 4o66** [comment]
This feature is in the new beta 2.0, and works far better than the 1.4.x tree (Full support for github, kerbalstuff, etc, but because of the way than URLs are handled in the program it is not just a matter of adding the site to a list.
Please see the URL in your other issue for a link to get access to the beta software.
